### PR TITLE
Setup Travis CI to build and deploy site.

### LINKED ISSUE #74: Use Travis CI to build Jekyll site
For reference https://github.com/mfenner/jekyll-travis

### PR DESCRIPTION
**Pull request by aydrian**
Resolves #74

Travis CI will test the generated site with [html-proofer](https://github.com/gjtorikian/html-proofer) for a Pull Request and will test and deploy the generated site when merged into develop. Once this is in place, the `master` branch will only contain the generated site. All future changes will need to be made in the `develop` branch.

After the PR is merged, we need to turn on Travis CI for the site and set `develop` as the default branch.

It is currently set up to use one of my personal access tokens for deploy. This can be changed.

### CODE REVIEW

**Comment by aydrian** [comment]
@richleland @jasonrhodes @rajumsys Thoughts?

**Comment by rajumsys** [comment]
looks good to me. Didn't pay attention to auto generated files (Gemfile.lock, Rakefile).

**Comment by aydrian** [comment]
@rajumsys Rakefile wasn't generated. I wrote that... ish.

**Comment by rajumsys** [comment]
> @rajumsys Rakefile wasn't generated. I wrote that... ish.
Damn! really? Reading the comments in top of the file, I thought it's auto generated. I'll look again. sorry

**Pull request merged**
